version: '3' 
services: 
    api:
        image: node:12.18.3
        volumes: 
            # API
            - ./api:/api
        ports: 
            - 3333:3333
        command: bash -c "cd /api && npm i && npm start"